### ISSUE TITLE
Testing tutorial on vagrant image.

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/dev#31]
If possible use multiple platforms to up the image.

**Comment by margoseltzer** [comment]
I got the vagrant VM up and running on my Mac. It took a couple of tries, because both vagrant and VirtualBox need to be uptodate. It also took _a long_ time to install. This isn't an issue for the tutorial where we will create full imagines, but it would nice if we could figure out how to make the provisioning a bit quicker.

Hardware Overview:

  Model Name:   MacBook Air
  Model Identifier: MacBookAir3,2
  Processor Name:   Intel Core 2 Duo
  Processor Speed:  2.13 GHz
  Number of Processors: 1
  Total Number of Cores:    2
  L2 Cache: 6 MB
  Memory:   4 GB
  Bus Speed:    1.07 GHz
  Boot ROM Version: MBA31.0061.B07
  SMC Version (system): 1.66f61
  Serial Number (system):   C02F903RDJDK
  Hardware UUID:    74AEDD40-E411-5BDC-98A3-09E5B984B589

OS X El Capitan Version 10.11.5
